[Fix] Accept RFC violations related to dots refs#134046
access-company/MimeKit pull request #1
Opened 2018-01-24 07:14 UTC by aTakayukiTaguchi

#134046：IMAPにて「xxx..x@ezweb.ne.jp」といったRFC違反のアドレスからメールを受信した際にアドレスが「不正フォーマット」と表示されてしまう
の修正を行いました。
修正内容はチケットに記載しています。

2018-01-25 02:22 UTC, aTakayukiMorita requested changes
テストコード書いてください。

2018-01-25 02:22 UTC, aTakayukiMorita commented on MimeKit/Utils/ParseUtils.cs
> +			index--;
ここは必要なのでしょうか？

2018-01-25 02:22 UTC, aTakayukiMorita commented on MimeKit/InternetAddress.cs
> +				if (text[index] == '@')
今回の修正で、なぜこれが必要になるのかわかりません。

2018-01-25 07:03 UTC, aTakayukiTaguchi commented on MimeKit/Utils/ParseUtils.cs
> +			return index > start;
index と start が同一になる正常ケースがありました。
index >= start に修正します。

2018-01-25 07:03 UTC, aTakayukiTaguchi commented on MimeKit/Utils/ParseUtils.cs
> +			index--;
連続したPeriodを許容するために追加しました。

2018-01-25 07:03 UTC, aTakayukiTaguchi commented on MimeKit/InternetAddress.cs
> +				if (text[index] == '@')
@の直線のPeriodを許容するため追加しました。

2018-01-25 10:17 UTC, aTakayukiTaguchi commented on MimeKit/Utils/ParseUtils.cs
> +		public static bool SkipWordAndPeriod (byte[] text, ref int index, int endIndex, bool throwOnError)
SkipWordを使用している別の箇所への影響を考慮し別メソッドにしました。

2018-01-25 10:19 UTC, aTakayukiTaguchi commented on MimeKit/InternetAddress.cs
> +					if (!ParseUtils.SkipWordAndPeriod (text, ref index, endIndex, throwOnError))
アドレスの先頭のPeriodを許容するために変更しました。

2018-01-25 10:21 UTC, aTakayukiTaguchi commented
@aTakayukiMorita 
テストコードを作成しました。レビューをお願い致します。
また、MimeKitの既存のテストコードは全てpassしています。

2018-01-26 02:14 UTC, aTakayukiMorita commented on UnitTests/GroupAddressTests.cs
> +				new TestCaseData ("<aaaa@access.co.jp>, <bbbb@access.co.jp>"),
社名を入れてしまうと、マージしてもらいにくくなりませんかね？

2018-01-26 07:56 UTC, aTakayukiTaguchi commented on UnitTests/GroupAddressTests.cs
> +				new TestCaseData ("<aaaa@access.co.jp>, <bbbb@access.co.jp>"),
GroupAddressに手を入れてないのでTestを削除しました。
InternetAddressとMailBoxAddressのテストケースにあった固有名詞は置換し別のワードに置き換えました。

2018-01-26 08:16 UTC, aTakayukiTaguchi commented
@aTakayukiMorita 
UnitTestで使われていた固有名詞を汎用的なものに変更しました。
レビューをお願い致します。

2018-01-26 08:26 UTC, aTakayukiMorita approved these changes

2018-01-26 08:27 UTC, merged